import Head from "next/head";
import Image from "next/image";
import EmailForm from "../components/email-form";
import styles from "../styles/Home.module.css";

import PrimeReact from "primereact/api";

export default function Home() {
  // active ripple effect
  PrimeReact.ripple = true;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <EmailForm />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
